### ISSUE TITLE
Provide OAS matrix page per publisher

### ISSUE THREAD

**Issue by richard-jones** [CottageLabs/oaspectrum#9]
Linked from the search interface and presented in a similar way as in the OAS brochure.

Note that there will be no explicit design phase for this project - we will take any graphics any guidelines for colours from the project team and aim for a clean layout, but there will not be an opportunity for any significant iteration on the look-and-feel of the site.

**Comment by gtananbaum** [comment]
See http://www.plos.org/open-access/howopenisit/ for appropriate files.

**Comment by richard-jones** [comment]
First draft of matrix page has been created, though we know of some desired changes:
- insert the matrix text into the table
- use neutral colours on scores
- take into account the different scales for each of the scores (see google doc)

@gtananbaum - assigning this to you for the moment for feedback on this page.

**Comment by gtananbaum** [comment]
Will provide feedback by midweek.

**Comment by richard-jones** [comment]
Feedback received and acted on.  Closing this out - any specific issues can be addressed separately, as the essential functionality is in place.
